# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 500

joint_pos_controller_1_l:
  type: "position_controllers/JointPositionController"
  joint: yumi_joint_1_l
joint_pos_controller_2_l:
  type: "position_controllers/JointPositionController"
  joint: yumi_joint_2_l
joint_pos_controller_7_l:
  type: "position_controllers/JointPositionController"
  joint: yumi_joint_7_l
joint_pos_controller_3_l:
  type: "position_controllers/JointPositionController"
  joint: yumi_joint_3_l
joint_pos_controller_4_l:
  type: "position_controllers/JointPositionController"
  joint: yumi_joint_4_l
joint_pos_controller_5_l:
  type: "position_controllers/JointPositionController"
  joint: yumi_joint_5_l
joint_pos_controller_6_l:
  type: "position_controllers/JointPositionController"
  joint: yumi_joint_6_l
joint_pos_controller_1_r:
  type: "position_controllers/JointPositionController"
  joint: yumi_joint_1_r
joint_pos_controller_2_r:
  type: "position_controllers/JointPositionController"
  joint: yumi_joint_2_r
joint_pos_controller_7_r:
  type: "position_controllers/JointPositionController"
  joint: yumi_joint_7_r
joint_pos_controller_3_r:
  type: "position_controllers/JointPositionController"
  joint: yumi_joint_3_r
joint_pos_controller_4_r:
  type: "position_controllers/JointPositionController"
  joint: yumi_joint_4_r
joint_pos_controller_5_r:
  type: "position_controllers/JointPositionController"
  joint: yumi_joint_5_r
joint_pos_controller_6_r:
  type: "position_controllers/JointPositionController"
  joint: yumi_joint_6_r


joint_group_pos_controller:
  type: "position_controllers/JointGroupPositionController"
  joints:
    - yumi_joint_1_r
    - yumi_joint_2_r
    - yumi_joint_7_r
    - yumi_joint_3_r
    - yumi_joint_4_r
    - yumi_joint_5_r
    - yumi_joint_6_r
    - yumi_joint_1_l
    - yumi_joint_2_l
    - yumi_joint_7_l
    - yumi_joint_3_l
    - yumi_joint_4_l
    - yumi_joint_5_l
    - yumi_joint_6_l

joint_group_pos_controller_l:
  type: "position_controllers/JointGroupPositionController"
  joints:
    - yumi_joint_1_l
    - yumi_joint_2_l
    - yumi_joint_7_l
    - yumi_joint_3_l
    - yumi_joint_4_l
    - yumi_joint_5_l
    - yumi_joint_6_l

joint_group_pos_controller_r:
  type: "position_controllers/JointGroupPositionController"
  joints:
    - yumi_joint_1_r
    - yumi_joint_2_r
    - yumi_joint_7_r
    - yumi_joint_3_r
    - yumi_joint_4_r
    - yumi_joint_5_r
    - yumi_joint_6_r

    
